"""Button class for states

Revision ID: 037359a3043a
Revises: 86eedd3b5968
Create Date: 2023-04-17 12:00:43.964443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037359a3043a'
down_revision = '86eedd3b5968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buttons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Boolean(), nullable=False),
    sa.Column('stop', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buttons'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('buttons')
    # ### end Alembic commands ###
