"""Adding picture column to Post

Revision ID: 38365b788ae1
Revises: 
Create Date: 2022-10-17 11:49:14.518381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38365b788ae1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('picture', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'picture')
    # ### end Alembic commands ###
