"""Adding separate run time class

Revision ID: 422c1dc43fad
Revises: 67c79e76b80c
Create Date: 2023-04-19 13:00:21.908455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '422c1dc43fad'
down_revision = '67c79e76b80c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_time', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('stop_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('run_time',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_time', schema=None) as batch_op:
        batch_op.alter_column('run_time',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('stop_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
