"""Start and stop time in status class

Revision ID: 5ea9e7651dbf
Revises: 037359a3043a
Create Date: 2023-04-18 02:58:21.684456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea9e7651dbf'
down_revision = '037359a3043a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('stop_time', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.drop_column('stop_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
