"""Adding separate run time class

Revision ID: 67c79e76b80c
Revises: 5ea9e7651dbf
Create Date: 2023-04-19 12:42:42.386998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c79e76b80c'
down_revision = '5ea9e7651dbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('stop_time', sa.DateTime(), nullable=False),
    sa.Column('run_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_time'))
    )
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.drop_column('stop_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('stop_time', sa.DATETIME(), nullable=False))

    op.drop_table('run_time')
    # ### end Alembic commands ###
