"""Adding Status class

Revision ID: 71e36a2c80fe
Revises: 69ee21e7d6e3
Create Date: 2022-11-07 15:11:19.799501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e36a2c80fe'
down_revision = '69ee21e7d6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connection', sa.Boolean(), nullable=False),
    sa.Column('moving', sa.Boolean(), nullable=False),
    sa.Column('picture_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status')
    # ### end Alembic commands ###
