"""Updating status object

Revision ID: 86eedd3b5968
Revises: 71e36a2c80fe
Create Date: 2023-04-15 19:16:47.926881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86eedd3b5968'
down_revision = '71e36a2c80fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_location_status_id_status'), 'status', ['status_id'], ['id'])

    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capturing', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('rotating', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('shifting', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('finishing', sa.Boolean(), nullable=False))
        batch_op.drop_column('moving')
        batch_op.drop_column('picture_count')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picture_count', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('moving', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('finishing')
        batch_op.drop_column('shifting')
        batch_op.drop_column('rotating')
        batch_op.drop_column('capturing')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_location_status_id_status'), type_='foreignkey')

    # ### end Alembic commands ###
